[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirect per tracciare le fonti
[[redirects]]
  from = "/mads"
  to = "/index.html?utm_source=mads"
  status = 200

[[redirects]]
  from = "/igs"
  to = "/index.html?utm_source=igs"
  status = 200

[[redirects]]
  from = "/fb"
  to = "/index.html?utm_source=fb"
  status = 200

[[redirects]]
  from = "/google"
  to = "/index.html?utm_source=google"
  status = 200

[[redirects]]
  from = "/tiktok"
  to = "/index.html?utm_source=tiktok"
  status = 200

[[redirects]]
  from = "/yt"
  to = "/index.html?utm_source=youtube"
  status = 200

[[redirects]]
  from = "/email"
  to = "/index.html?utm_source=email"
  status = 200

[[redirects]]
  from = "/sms"
  to = "/index.html?utm_source=sms"
  status = 200

# Redirect per thank you page
[[redirects]]
  from = "/thankyou-1"
  to = "/thankyou.html"
  status = 200